############# English navigation ##############

# main menu

[[main]]
name = "首页"
url = ""
weight = 1

[[main]]
name = "关于我"
url = "about/"
weight = 2

[[main]]
name = "目录"
url = "categories/"
weight = 3

[[main]]
name = "联系我"
url = "contact/"
weight = 5

[[main]]
name = "文章"
url = "blog/"
weight = 4

# dropdown menu
[[main]]
name = "项目"
weight = 6
hasChildren = true

  # dropdown item
  [[main]]
  parent = "项目"
  name = "项目一"
  url = "/"

  [[main]]
  parent = "项目"
  name = "项目二"
  url = "/"
